# Generated by Django 5.1.5 on 2025-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('client_phone', models.CharField(db_index=True, max_length=20)),
                ('client_telegram', models.CharField(blank=True, max_length=40)),
                ('client_viber', models.CharField(blank=True, max_length=20)),
                ('client_whatsapp', models.CharField(blank=True, max_length=20)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('time_demand', models.DateField(blank=True)),
                ('device', models.CharField(max_length=255)),
                ('defect', models.TextField(max_length=400)),
                ('device_password', models.CharField(blank=True, max_length=50)),
                ('device_exterior', models.TextField(blank=True, max_length=400)),
                ('initial_price', models.CharField(blank=True, max_length=10)),
                ('prepaid', models.FloatField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('AC', 'Активен'), ('RD', 'Готов'), ('AW', 'Выдан '), ('NP', 'Выдан без оплаты'), ('WR', 'Гарантийный')], default='AC', max_length=2)),
                ('work', models.CharField(blank=True, max_length=255)),
                ('work_price', models.FloatField(blank=True, max_length=10)),
                ('work_warranty', models.FloatField(blank=True, max_length=2)),
                ('work1', models.CharField(blank=True, max_length=255)),
                ('work_price1', models.FloatField(blank=True, max_length=10)),
                ('work_warranty1', models.FloatField(blank=True, max_length=2)),
                ('work2', models.CharField(blank=True, max_length=255)),
                ('work_price2', models.FloatField(blank=True, max_length=10)),
                ('work_warranty2', models.FloatField(blank=True, max_length=2)),
                ('work3', models.CharField(blank=True, max_length=255)),
                ('work_price3', models.FloatField(blank=True, max_length=10)),
                ('work_warranty3', models.FloatField(blank=True, max_length=2)),
                ('work4', models.CharField(blank=True, max_length=255)),
                ('work_price4', models.FloatField(blank=True, max_length=10)),
                ('work_warranty4', models.FloatField(blank=True, max_length=2)),
                ('work5', models.CharField(blank=True, max_length=255)),
                ('work_price5', models.FloatField(blank=True, max_length=10)),
                ('work_warranty5', models.FloatField(blank=True, max_length=2)),
                ('work6', models.CharField(blank=True, max_length=255)),
                ('work_price6', models.FloatField(blank=True, max_length=10)),
                ('work_warranty6', models.FloatField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='fixorder_or_time_cr_d84a42_idx')],
            },
        ),
    ]
