# Generated by Django 5.1.5 on 2025-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_telegram',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_viber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_exterior',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_demand',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price1',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price2',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price3',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price4',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price5',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price6',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty1',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty5',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty6',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
    ]
