# Generated by Django 5.1.5 on 2025-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0002_alter_order_client_telegram_alter_order_client_viber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ФИО клиента'),
        ),
    ]
