# Generated by Django 5.1.5 on 2025-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0003_alter_order_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_away',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_telegram',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_viber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Viber клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whattsapp клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='defect',
            field=models.TextField(max_length=400, verbose_name='Неисправность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.CharField(max_length=255, verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_exterior',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Внешний вид'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ориентировочная стоимость ремонта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AC', 'Активен'), ('RD', 'Готов'), ('AW', 'Выдан '), ('NP', 'Выдан без оплаты'), ('WR', 'Гарантийный')], default='AC', max_length=2, verbose_name='Статус ремонта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_demand',
            field=models.DateField(blank=True, null=True, verbose_name='Срок ремонта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполненная работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price1',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price2',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price3',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price4',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price5',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_price6',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty1',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty2',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty3',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty4',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty5',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty6',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
    ]
