# Generated by Django 5.1.5 on 2025-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0004_order_time_away_alter_order_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
