# Generated by Django 5.1.5 on 2025-01-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0005_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
