# Generated by Django 5.1.5 on 2025-01-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0007_orderstatus_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_order', to='fixorder.orderstatus', verbose_name='Статус ремонта'),
        ),
    ]
