# Generated by Django 5.1.5 on 2025-01-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='conclusion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заключение мастера'),
        ),
    ]
