# Generated by Django 5.1.5 on 2025-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0010_order_remain_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_warranty',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Выполненная работа'),
        ),
    ]
