# Generated by Django 5.1.5 on 2025-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0011_alter_order_work_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remain_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Осталось оплатить'),
        ),
    ]
