# Generated by Django 5.1.5 on 2025-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0012_alter_order_remain_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ориентировочная стоимость'),
        ),
    ]
