# Generated by Django 5.1.5 on 2025-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0013_alter_order_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_phone1',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Дополнительный номер'),
        ),
    ]
