# Generated by Django 5.1.5 on 2025-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0014_order_client_phone1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название компании')),
                ('official_name', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='Юридическое наименование')),
                ('unp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='УНП')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Контактный номер')),
                ('phone1', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Контактный номер')),
                ('phone2', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Контактный номер')),
                ('telegram', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram')),
                ('viber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Viber')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Whattsapp')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Электронная почта')),
                ('adress', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='Адрес')),
                ('postal_adress', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Почтовый адрес')),
                ('official_adress', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Юридический адрес')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Логотип компании')),
            ],
        ),
    ]
