# Generated by Django 5.1.5 on 2025-02-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0015_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='official_adress',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='official_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Юридическое наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_adress',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почтовый адрес'),
        ),
    ]
