# Generated by Django 5.1.5 on 2025-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0016_alter_company_adress_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Логотип компании'),
        ),
    ]
