# Generated by Django 5.1.5 on 2025-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0018_alter_company_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Логотип компании'),
        ),
    ]
