# Generated by Django 5.1.5 on 2025-03-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0020_client_remove_order_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone1',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Дополнительный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='fixorder.client', verbose_name='Клиент'),
        ),
    ]
