# Generated by Django 5.1.5 on 2025-03-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0024_alter_order_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='fixorder.client', verbose_name='Клиент'),
        ),
    ]
