# Generated by Django 5.1.5 on 2025-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0025_alter_order_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ФИО клиента'),
        ),
    ]
