# Generated by Django 5.1.5 on 2025-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0026_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ФИО клиента'),
        ),
    ]
