# Generated by Django 5.1.5 on 2025-03-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0027_alter_client_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='work_warranty',
            field=models.FloatField(blank=True, max_length=2, null=True, verbose_name='Гарантия'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='fixorder_cl_name_cc36cc_idx'),
        ),
    ]
