# Generated by Django 5.1.5 on 2025-03-24 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0029_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('1', 'Работает'), ('2', 'Отсутствует'), ('3', 'Не работает')], default='1', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_fire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_hire',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
