# Generated by Django 5.1.5 on 2025-03-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0031_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='fixorder.client', verbose_name='Клиент'),
        ),
    ]
