# Generated by Django 5.1.5 on 2025-03-31 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0032_alter_order_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to='fixorder.employee', verbose_name='Исполнитель'),
        ),
    ]
