# Generated by Django 5.1.5 on 2025-04-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0033_order_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание работы')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('warranty', models.CharField(max_length=20, verbose_name='Гарантия')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='work',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_price6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_warranty6',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='fixorder_or_status__fed1c7_idx'),
        ),
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='fixorder.order', verbose_name='Заказ'),
        ),
    ]
