# Generated by Django 5.1.5 on 2025-04-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0036_alter_work_warranty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typicalwork',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='typicalwork',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Вид работы'),
        ),
    ]
