# Generated by Django 5.1.5 on 2025-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0037_alter_typicalwork_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предоплата'),
        ),
    ]
