# Generated by Django 5.1.5 on 2025-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0038_alter_work_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prepaid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Предоплата'),
        ),
    ]
