# Generated by Django 5.1.5 on 2025-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixorder', '0038_alter_order_prepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='income_data',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Общая информация для приемной квитанции'),
        ),
        migrations.AddField(
            model_name='company',
            name='warranty_data',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Общая информация для приемной квитанции'),
        ),
    ]
